services:
  mongo-server:
    image: mongo:latest
    container_name: mongo-server
    ports:
      - "44444:27017"
    volumes:
      - mongodb-data:/data/db

  api:
    build: ./MongoApi
    container_name: mongo-api
    ports:
      - "8080:8080"
    environment:
      - MongoDB__ConnectionString=mongodb://mongo-server:27017
      - MongoDB__DatabaseName=restore
    depends_on:
      - mongo-server

volumes:
  mongodb-data:
