# Build stage
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /source
 
COPY . .
RUN dotnet restore
RUN dotnet publish -c Release -o out
 
# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app
COPY --from=build /source/out ./
 
ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080
 
ENTRYPOINT ["dotnet", "MongoApi.dll"]